/*
CURSO: BASE DE DATOS ORACLE DATABASE BY VICTOR RAMOS
SITIO: UDEMY
FECHA: 30-31/03/2024
*/

/*
SECCION 3 - TABLAS DE DATOS

*TIPOS DE DATOS
CHAR
NCHAR
NVARCHAR2
VARCHAR2
VARCHAR -> MAS USADO. ALFANUMERICO (LETRAS/NUMEROS/CARACT.)
LONG
RAW
LONG RAW

*DATOS NUMERICOS
NUMBER * -> NUMERO (ENTERO,DECIMAL)
INT * -> ENTERO
DECIMAL * -> CON DECIMAL
BINARY_FLOAT
BINARY_DOUBLE

DATOS FECHAS 
DATE
TIMESTAMP
TIMESTAMP WITH TIME ZONE
INTERVAL
*/

// CREACION DE TABLAS CLASE-06
CREATE TABLE TB_CATEGORIAS(CODIGO_CA INT, DESCRIPCION_CA VARCHAR(30));
CREATE TABLE TB_MEDIDAS(CODIGO_MD NUMBER(3,0), ABREVIATURA_MD VARCHAR(3), DESCRIPCION_MD VARCHAR(20));
CREATE TABLE TB_ARTICULOS(CODIGO_AR NUMBER(5,0),
                          DESCRIPCION_AR VARCHAR2(50),
                          MARCA VARCHAR2(30),
                          CODIGO_ME NUMBER(3,0),
                          CODIGO_CA NUMBER(4,0),
                          FECHA_AR DATE,
                          STOCK_ACTUAL DECIMAL(10,2));

// ELIMINACION TABLA DE DATOS CLASE-07
DROP TABLE TB_MEDIDAS;
DROP TABLE TB_CATEGORIAS;
DROP TABLE TB_ARTICULOS;

// RE-CREACION DE TABLAS CLASE-08
CREATE  TABLE TB_CATEGORIAS(CODIGO_CA NUMBER(4,0), DESCRIPCION_CA VARCHAR(30));
CREATE TABLE TB_MEDIDAS(CODIGO_ME NUMBER(3,0), 
                        ABREVIATURA_ME VARCHAR(3),
                        DESCRIPCION_ME VARCHAR(20));
CREATE TABLE TB_ARTICULOS(CODIGO_AR NUMBER(6,0),
                          DESCRIPCION_AR VARCHAR(50),
                          MARCA_AR VARCHAR(30));
                          
// ALTERACION DE ESTRUCTURA DE TABLA CLASE-09
ALTER TABLE TB_CATEGORIAS MODIFY (CODIGO_CA NOT NULL); //-> NO ADMITE VALORES NULL
ALTER TABLE TB_CATEGORIAS MODIFY (DESCRIPCION_CA NOT NULL);
ALTER TABLE TB_MEDIDAS MODIFY (CODIGO_ME NOT NULL);
ALTER TABLE TB_ARTICULOS MODIFY (CODIGO_AR NOT NULL);

ALTER TABLE TB_MEDIDAS MODIFY (DESCRIPCION_ME VARCHAR(30)); //-> CAMBIO LONGITUD DE VARCHAR

ALTER TABLE TB_ARTICULOS DROP COLUMN MARCA_AR; //-> ELIMINO UNA COLUMNA

ALTER TABLE TB_ARTICULOS MODIFY CODIGO_AR NUMBER(6,0) DEFAULT 0; //-> MANTENGO LOS 6 DIGITOS PERMITIDOS PERO CAMBIO VALOR DEFAULT
ALTER TABLE TB_CATEGORIAS MODIFY CODIGO_CA NUMBER(4,0) DEFAULT 0;
ALTER TABLE TB_MEDIDAS MODIFY CODIGO_ME NUMBER(3,0) DEFAULT 0;

ALTER TABLE TB_ARTICULOS ADD MARCA_AR VARCHAR(30); //-> AGREGO COLUMNA MARCA
ALTER TABLE TB_ARTICULOS ADD (CODIGO_ME NUMBER(3,0), CODIGO_CA NUMBER(4,0)); //-> AGREGO 2 COLUMNAS

// AGREGAR CLAVE PRIMARIA CLASE-10
ALTER TABLE TB_ARTICULOS ADD PRIMARY KEY (CODIGO_AR);
ALTER TABLE TB_CATEGORIAS ADD PRIMARY KEY (CODIGO_CA);
ALTER TABLE TB_MEDIDAS ADD PRIMARY KEY (CODIGO_ME);

// AGREGAR CLAVE FORENEA CLASE-11
/* TABLA HIJA: ARTICULOS YA QUE DEPENDE DE LAS OTRAS 2 TABLAS
   TABLAS MADRES: MEDIDA Y CATEGORIAS (NO DEPENDEN DE OTRAS TABLAS)
   
   * LA CLAVE FORANEA SE APLICA SOBRE LAS TABLAS HIJAS (DEPENDEN DE OTRAS TABLAS)
   
   * LA CLAVE FORANEA SE GENERA PARA GARANTIZAR QUE LA INFORMACION SEA FIABLE 
     NO PUEDO CREAR UNA MEDIDA EN ARTICULOS SI NO EXISTE EN LA TABLA MEDIDA*/
ALTER TABLE TB_ARTICULOS 
ADD CONSTRAINT FK_01
FOREIGN KEY (CODIGO_ME)
REFERENCES TB_MEDIDAS(CODIGO_ME); //-> ES IGUAL A CODIGO_ME DE TABLA MEDIDAS

ALTER TABLE TB_ARTICULOS 
ADD CONSTRAINT FK_02
FOREIGN KEY (CODIGO_CA)
REFERENCES TB_CATEGORIAS(CODIGO_CA);

// COLUMNAS IDENTITY CLASE-12
/*LAS COLUMNAS IDENTITY SON AQUELLAS QUE LOS VALORES DE CODIGO SE VAN INCREMENTANDO DE FORMA AUTOMATICA*/
CREATE TABLE TB_ALMACENES(CODIGO_AL NUMBER(2,0)GENERATED ALWAYS AS IDENTITY,
                          DESCRIPCION VARCHAR(32));